### ISSUE TITLE
Change the Travis to run differently the acceptance test

### ISSUE THREAD

**Issue by aaltat** [robotframework/SeleniumLibrary#713]
Because there was some unexpected problems with Travis and the accessing the encrypted information (the Sauce Labs credentials) [1] we need to change how we run acceptance tests from the original plan.

 * For each PR, run with Firefox (provided by Travis), selenium 2/3 and Python 2/3. 
 * Create nightly/weekly build to run from master and run by using Sauce Labs by using different browsers.

[1] https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by aaltat** [comment]
We could define the `.travis.yaml`like this: 
```
language: python
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - pip install robotframework
  - pip install future
matrix:
  include:
    - python: "2.7" # For PR and cron
      env:
        - BROWSER=chrome
        - SELENIUM=2.53.6
    - python: "3.3" # For PR and cron
      env:
        - BROWSER=chrome
        - SELENIUM=2.53.6
    - python: "3.3" # For PR and cron
      env:
        - BROWSER=chrome
        - SELENIUM=3.0.2
    - python: "3.3" # For cron
      env:
        - BROWSER=firefox
        - SELENIUM=2.53.6
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - pip install selenium==$SELENIUM
script: python run_me.py $BROWSER
```
And then run test runner we could do something like this:
```
from __future__ import print_function
import os
import sys
from selenium import webdriver

print('start')
browser = sys.argv[1]
selenium = os.environ.get('SELENIUM')
print(browser)
print(selenium)
travis_event_type = os.environ.get('TRAVIS_EVENT_TYPE')

if travis_event_type == 'cron':
    print(os.environ.get('SAUCE_ACCESS_KEY'))
    print(os.environ.get('SAUCE_USERNAME'))
    # and other sstuff run with Sauce labs
elif travis_event_type != 'cron' and browser != 'chorme':
    # exit fast if trying to use other browser than chrome
    print(
        'No cron, exting test with selenium-{} and {} from Sauce'.format(
            selenium,
            browser
        )
    )
    sys.exit(0)
else:
    print('Running test for PR with {} using selenium'.format(browser, selenium))
    driver = webdriver.Chrome()
    driver.get("http://www.python.org")
    driver.close()

print ('end')
sys.exit(0)
```
